### PR TITLE
First Client Push

### PR DESCRIPTION
**Pull request by taradactyl27**
- login, home page working
- ui changes
- navigation in place

### CODE REVIEW

**Review by boubascript — COMMENTED** [review]
[nitpick] looks like you accidentally moved the readme file into the client folder btw, can you move it back?

**Comment by taradactyl27** [comment]
done

**Comment by taradactyl27** [comment]
null safety finished

**Review by boubascript — APPROVED** [review]
LGTM ! move fast break things wooo

**Pull request merged**
